version: '3.4'

services:
  caller.api:
    image: ${DOCKER_REGISTRY}caller.api
    build:
      context: .
      dockerfile: Caller.Api/Dockerfile
  caller.worker:
    image: ${DOCKER_REGISTRY}caller.worker
    build:
      context: .
      dockerfile: Caller.Worker/Dockerfile
